### ISSUE TITLE
Making a "OKAY" Config Module

### ISSUE THREAD

**Issue by whoastonic** [whoastonic/Morgaine#1]
## The Problem:

While making the `config` module there's a lot of mistakes and undecided features... such as loading config from the environment which in theory is okay but very brittle in design; You can also load config from a config file that's formatted in [YML](https://yaml.org/), but in design, we started to load from the environment first then load from file... which again sounded good in the head, but a little bit too brittle to put in this application. Doing these like this loses consistency, practicality, and predictability.

## The Answer:

Most likely to improve consistency, we just load the config from a config file (`.morgaine.yaml`). This config will store things such as server-credentials, database-credentials, API Keys, TSL/SSL certs, etc. To improve practicality we make sure the server can read the config in a root path... such as: `~/.morgaine.yml` or `~/.config/.morgaine.yml` this would increase practically and workspace cleanliness; once going into `PRODUCTION` or when `MORG_ENV` has a value of `prod` or `production` (this isn't case-sensitive), we'll load the config from the file into `ENV VARIABLES` (if running with docker and secrets are stored, these are also loaded into the env when going into production). To improve predictability, the config must follow these guidelines so those future developers (or yourself) don't forget what everything does:

```yml
# this just an example
server:
  port: 8080
  host: 127.0.0.1
cache:
  # if using memory-store
  # host: memory
  # if using redis
  host: 127.0.0.1
  port: 6894
  password: redis-password12
database_url: postgresql://127.0.0.1@username:password/name
```
